CREATE TABLE developers (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    name VARCHAR(100) NOT NULL
);

CREATE TABLE games (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    title VARCHAR(100) NOT NULL,
    developer_id INTEGER NOT NULL REFERENCES developers(id) ON DELETE CASCADE
);

CREATE TABLE heroes (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(100) NOT NULL
);

CREATE TABLE villains (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(100) NOT NULL
);

CREATE TABLE scores (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    game_id INTEGER UNIQUE NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    metascore INTEGER NOT NULL,
    userscore NUMERIC(3, 1) NOT NULL
);

CREATE TABLE platforms (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
    name VARCHAR(100) NOT NULL
);

CREATE TABLE game_platforms (
    game_id INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    platform_id INTEGER NOT NULL REFERENCES platforms(id) ON DELETE CASCADE,
    PRIMARY KEY (game_id, platform_id)
);

